#!/usr/bin/env python3
"""
Run the whole pipeline against generated data, and check the numbers.

    python scripts/mock_jira.py --port 8089 &
    python scripts/demo.py

Two things this does that the unit tests cannot:

1. It exercises the path between the API and the DataFrame — pagination,
   changelog parsing, field extraction, the JQL that gets built. Handing the
   analyser a ready-made frame skips exactly the part most likely to be wrong.
2. It checks the metrics against facts known about the generated data, rather
   than against whatever the code happens to produce.

Everything is generated by scripts/mock_jira.py with a fixed seed. No figure
here comes from a real JIRA, and none of it describes a real team.
"""

from __future__ import annotations

import os
import sys
import warnings

warnings.filterwarnings("ignore")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

DEFAULTS = {
    "JIRA_SERVER": "http://127.0.0.1:8089",
    "JIRA_USERNAME": "demo",
    "JIRA_API_KEY": "demo",
    "CURRENT_RELEASE": "REL-25",
    "DEFECT_ISSUE_TYPES": "Bug,Defect",
    "CRITICAL_ISSUE_TYPES": "Defect",
    "SEVERITY_FIELD": "99999",
}
for key, value in DEFAULTS.items():
    os.environ.setdefault(key, value)

from config import Config           # noqa: E402
from defect_analyzer import DefectAnalyzer   # noqa: E402
from jira_client import QuickJiraCollector, reporting_quality  # noqa: E402

checks: list[tuple[str, bool]] = []


def check(label: str, passed: bool) -> None:
    checks.append((label, bool(passed)))
    print(f"  {'PASS' if passed else 'FAIL'}  {label}")


def rule(title: str) -> None:
    print(f"\n--- {title} " + "-" * max(0, 62 - len(title)))


def main() -> int:
    rule("collecting from the API")
    try:
        collector = QuickJiraCollector()
        df = collector.get_defects_quick()
    except Exception as exc:  # noqa: BLE001
        print(f"\nCannot reach the mock JIRA at {Config.JIRA_SERVER}: {exc}")
        print("Start it with: python scripts/mock_jira.py --port 8089")
        return 2

    print()
    check("every page was followed, not just the first", len(df) == 240)
    check("the changelog was read (some defects have reopens)",
          df["reopen_count"].sum() > 0)
    check("reopen counts are plausible, not everything at once",
          0 < (df["reopen_count"] > 0).mean() < 0.5)

    rule("reopens: the signal a count cannot show")
    repeat = df[df["reopen_count"] > 0]
    print(f"  {len(repeat)} of {len(df)} defects came back after being closed "
          f"({len(repeat) / len(df) * 100:.1f}%)")
    for count, group in sorted(repeat.groupby("reopen_count"), key=lambda kv: -kv[0]):
        print(f"    reopened {count}x: {len(group)} defects")
    worst = df.nlargest(3, "reopen_count")[["key", "reopen_count", "status"]]
    print("  most reopened:")
    for _, row in worst.iterrows():
        print(f"    {row['key']:<12} {row['reopen_count']} reopens, now {row['status']}")

    rule("write-up quality")
    scored = [reporting_quality(r) for r in df.to_dict("records")]
    poor = [s for s in scored if s["quality_score"] < 50]
    print(f"  {len(poor)} of {len(scored)} defects score below 50% "
          f"({len(poor) / len(scored) * 100:.1f}%)")
    missing: dict[str, int] = {}
    for s in scored:
        for field in s["missing"]:
            missing[field] = missing.get(field, 0) + 1
    for field, n in sorted(missing.items(), key=lambda kv: -kv[1]):
        print(f"    {field:<28} missing on {n}")
    check("quality scoring separates good write-ups from bad",
          0 < len(poor) < len(scored))

    rule("summary metrics")
    analyzer = DefectAnalyzer()
    full = analyzer.get_all_release_defects()
    summary = analyzer.get_comprehensive_summary(full)
    for key in ["total_defects", "open_defects", "resolved_defects",
                "resolution_rate", "avg_age_days", "avg_age_open",
                "unassigned_rate", "avg_resolution_time_hours"]:
        print(f"  {key:<28} {summary[key]}")

    print()
    check("open + resolved accounts for every defect",
          summary["open_defects"] + summary["resolved_defects"] == summary["total_defects"])
    check("resolution rate matches the counts beneath it",
          abs(summary["resolution_rate"]
              - summary["resolved_defects"] / summary["total_defects"] * 100) < 0.1)
    check("the rate is a percentage, not a fraction", 1 < summary["resolution_rate"] <= 100)
    check("Closed and Done count as resolved, not just the literal 'Resolved'",
          summary["resolved_defects"] > len(full[full["status"] == "Resolved"]))
    check("open defects are older on average than the whole set",
          summary["avg_age_open"] >= summary["avg_age_days"])

    rule("project health")
    health = analyzer.get_detailed_project_analysis(full)
    for name, stats in sorted(health.items(), key=lambda kv: kv[1]["health_score"]):
        print(f"  {name:<10} health {stats['health_score']:.3f}  "
              f"open {int(stats['open_defects']):>3}/{int(stats['total_defects']):<3}  "
              f"avg age of open {stats['avg_age_open_days']:.0f}d")
    check("health scores stay within 0..1",
          all(0 <= s["health_score"] <= 1 for s in health.values()))
    # The fix this checks: age used to be averaged over resolved defects too,
    # and age is "now minus created", so a resolved defect kept ageing forever.
    # A project that fixed everything promptly still decayed month after month.
    # Contradicting my first attempt at this check, avg_age_open is legitimately
    # HIGHER than avg_age_days here — open defects really are the older ones —
    # so comparing the two proves nothing. Build the case that does.
    all_fixed = full[full["is_resolved"]].copy()
    all_fixed["project"] = "ALLFIXED"
    fixed_health = analyzer.get_detailed_project_analysis(all_fixed)["ALLFIXED"]
    print(f"  a project with every defect resolved: health "
          f"{fixed_health['health_score']:.3f}, "
          f"avg age of open {fixed_health['avg_age_open_days']:.0f}d "
          f"(avg age of all {fixed_health['avg_age_days']:.0f}d)")
    check("a project with everything resolved has no open-defect age",
          fixed_health["avg_age_open_days"] == 0)
    # Not 1.0: the score also weights how many defects were critical, and those
    # existed even though they are now fixed. Whether a resolved critical should
    # still count against a project is a judgement, not a defect — so the check
    # is that the age term contributes in full, and that this project scores
    # better than any project still carrying open work.
    check("it scores higher than every project with open defects",
          fixed_health["health_score"] > max(s["health_score"] for s in health.values()))
    check("the ageing term contributes in full when nothing is open",
          abs(fixed_health["health_score"]
              - ((1 - 0) * 0.4
                 + (1 - fixed_health["critical_defects"] / fixed_health["total_defects"]) * 0.3
                 + 0.3)) < 0.002)

    rule("empty input")
    empty = full.iloc[0:0]
    empty_summary = analyzer.get_comprehensive_summary(empty)
    print(f"  resolution_rate on an empty set: {empty_summary['resolution_rate']}")
    check("an empty set reports unknown, not zero and not NaN",
          empty_summary["resolution_rate"] is None)
    check("counts are still zero", empty_summary["total_defects"] == 0)

    failed = [label for label, ok in checks if not ok]
    print("\n" + "-" * 70)
    print(f"{len(checks) - len(failed)} of {len(checks)} checks passed")
    for label in failed:
        print(f"  FAILED: {label}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
